ibm-websphere-liberty:
  ###############################################################################
  # Licensed Materials - Property of IBM.
  # Copyright IBM Corporation 2017. All Rights Reserved.
  # U.S. Government Users Restricted Rights - Use, duplication or disclosure
  # restricted by GSA ADP Schedule Contract with IBM Corp.
  #
  # Contributors:
  #  IBM Corporation - initial API and implementation
  ###############################################################################


  ###############################################################################
  ## Common image variables
  ###############################################################################
  image:
    repository: registry.ng.bluemix.net/jagraj/ns2/acmeair-bookingservice-java

ibm-mongodb-dev:

  nameOverride: ""
  dataVolume:
    name: "dv"